# permissions for end users to edit scheduledscalings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: scheduledscaling-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: tortoise
    app.kubernetes.io/part-of: tortoise
    app.kubernetes.io/managed-by: kustomize
  name: scheduledscaling-editor-role
rules:
- apiGroups:
  - autoscaling.mercari.com
  resources:
  - scheduledscalings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.mercari.com
  resources:
  - scheduledscalings/status
  verbs:
  - get
